from dataclasses import dataclass
from typing import Dict, List


@dataclass
class ThematicStockItem:
    """Represents a curated stock discovery item with beginner-friendly context."""
    ticker: str
    name: str
    approx_price: str
    category_id: str  # 'penny', 'safe', 'new', 'trending', 'future'
    category_title: str
    catalyst_driver: str
    why_it_matters: str
    risk_level: str
    risk_badge: str  # '🟢 Safe', '🟡 Moderate', '🔴 High Risk'


# =============================================================================
# INDIAN MARKETS (NSE / BSE) THEMATIC RADAR — EXPANDED INSTITUTIONAL UNIVERSE
# =============================================================================
INDIAN_THEMATIC_RADAR: Dict[str, List[ThematicStockItem]] = {
    "penny": [
        ThematicStockItem(
            ticker="IDEA.NS",
            name="Vodafone Idea",
            approx_price="₹7.40",
            category_id="penny",
            category_title="🪙 Small-Priced (< ₹100)",
            catalyst_driver="Government debt-to-equity conversion and ₹20,000 Cr capex rollout for 5G network expansion.",
            why_it_matters="Ultra low-priced telecom play. High turnaround leverage, but debt burden requires cautious sizing.",
            risk_level="High Risk / Speculative",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="YESBANK.NS",
            name="Yes Bank",
            approx_price="₹19.80",
            category_id="penny",
            category_title="🪙 Small-Priced (< ₹100)",
            catalyst_driver="Post-restructuring balance sheet cleanup backed by SBI and surging low-cost retail CASA deposits.",
            why_it_matters="Accessible sub-₹20 entry. Old bad loans are largely resolved, entering a normalized growth phase.",
            risk_level="Speculative Recovery",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="SOUTHBANK.NS",
            name="South Indian Bank",
            approx_price="₹24.50",
            category_id="penny",
            category_title="🪙 Small-Priced (< ₹100)",
            catalyst_driver="Sharp turnaround in net interest margins and digital SME lending across South India.",
            why_it_matters="Attractive price-to-book valuation with clean NPA reduction under new professional management.",
            risk_level="Value Turnaround",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="RPOWER.NS",
            name="Reliance Power",
            approx_price="₹38.50",
            category_id="penny",
            category_title="🪙 Small-Priced (< ₹100)",
            catalyst_driver="Accelerated debt settlement with commercial lenders and planned expansion into utility solar.",
            why_it_matters="Rapidly deleveraging power producer benefiting from India's peak electricity demand.",
            risk_level="High Volatility",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="UCOBANK.NS",
            name="UCO Bank",
            approx_price="₹43.00",
            category_id="penny",
            category_title="🪙 Small-Priced (< ₹100)",
            catalyst_driver="Public sector bank experiencing sustained credit quality improvement and rising dividend yields.",
            why_it_matters="State-owned bank with sovereign backing trading at modest multiples to book value.",
            risk_level="Moderate",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="IOB.NS",
            name="Indian Overseas Bank",
            approx_price="₹52.00",
            category_id="penny",
            category_title="🪙 Small-Priced (< ₹100)",
            catalyst_driver="Exit from RBI prompt corrective action with record low gross NPA ratios.",
            why_it_matters="Beneficiary of the multi-year Indian banking revival cycle with strong retail presence.",
            risk_level="Moderate",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="SUZLON.NS",
            name="Suzlon Energy",
            approx_price="₹58.20",
            category_id="penny",
            category_title="🪙 Small-Priced (< ₹100)",
            catalyst_driver="Completely net debt-free with an all-time record order book exceeding 4 GW for wind turbines.",
            why_it_matters="The undisputed leader in domestic wind energy infrastructure, perfectly aligned with green targets.",
            risk_level="Growth Turnaround",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="OLAEL.NS",
            name="Ola Electric Mobility",
            approx_price="₹68.00",
            category_id="penny",
            category_title="🪙 Small-Priced (< ₹100)",
            catalyst_driver="Scale ramp at its Futurefactory and indigenous Bharat 4680 battery cell manufacturing.",
            why_it_matters="Dominant market share in Indian electric two-wheelers with direct vertically integrated cell tech.",
            risk_level="High Growth / Early Stage",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="NHPC.NS",
            name="NHPC Ltd",
            approx_price="₹88.50",
            category_id="penny",
            category_title="🪙 Small-Priced (< ₹100)",
            catalyst_driver="Government-owned hydropower utility commanding long-term Power Purchase Agreements (PPAs).",
            why_it_matters="Sub-₹100 defensive blue-chip utility backed by sovereign guarantees with solid dividend payouts.",
            risk_level="Low to Moderate",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="NBCC.NS",
            name="NBCC (India) Ltd",
            approx_price="₹92.00",
            category_id="penny",
            category_title="🪙 Small-Priced (< ₹100)",
            catalyst_driver="₹70,000+ Cr state construction order book including stalled housing redevelopment projects.",
            why_it_matters="Debt-free public sector enterprise with an asset-light, cost-plus project management business model.",
            risk_level="Moderate",
            risk_badge="🟢 Solid Orderbook",
        ),
        ThematicStockItem(
            ticker="SJVN.NS",
            name="SJVN Ltd",
            approx_price="₹98.00",
            category_id="penny",
            category_title="🪙 Small-Priced (< ₹100)",
            catalyst_driver="Rapidly expanding renewable portfolio spanning hydro, solar, and wind across India and Nepal.",
            why_it_matters="Key executing PSU for national renewable energy mandates with strong operating cash flow.",
            risk_level="Moderate",
            risk_badge="🟢 Safe Dividend",
        ),
    ],

    "safe": [
        ThematicStockItem(
            ticker="RELIANCE.NS",
            name="Reliance Industries",
            approx_price="₹1,230.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="India's largest conglomerate spanning Oil-to-Chemicals, Jio 5G, and Reliance Retail leadership.",
            why_it_matters="Virtually recession-proof. Anchors the Nifty 50 and is the foundational pillar of Indian markets.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="TCS.NS",
            name="Tata Consultancy Services",
            approx_price="₹3,950.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Zero net debt, unmatched 35%+ Return on Equity, and consistent high dividend distributions.",
            why_it_matters="When global markets wobble, TCS protects capital thanks to multi-billion dollar mission-critical contracts.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="HDFCBANK.NS",
            name="HDFC Bank",
            approx_price="₹1,680.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Premier private banking institution with conservative underwriting and flawless asset quality.",
            why_it_matters="The primary destination for global institutional capital deploying into Indian economic growth.",
            risk_level="Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="INFY.NS",
            name="Infosys",
            approx_price="₹1,850.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Global generative AI enterprise transformation programs and massive shareholder capital return via buybacks.",
            why_it_matters="Debt-free tech powerhouse with diversified multi-national clientele across US and Europe.",
            risk_level="Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="ICICIBANK.NS",
            name="ICICI Bank",
            approx_price="₹1,250.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Industry-leading return on assets (ROA > 2.3%) driven by high-margin retail loans and digitization.",
            why_it_matters="Consistent top-tier performer in the Indian banking system with immaculate credit provisioning.",
            risk_level="Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="ITC.NS",
            name="ITC Limited",
            approx_price="₹465.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Monopolistic cigarette cash flow machine funding rapid growth in packaged FMCG, hotels, and paper.",
            why_it_matters="Legendary for capital protection during broad market corrections and generous dividend payouts.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="LT.NS",
            name="Larsen & Toubro",
            approx_price="₹3,600.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Supreme monopoly in mega-infrastructure, defense engineering, and Middle East EPC projects.",
            why_it_matters="If India builds a highway, bridge, metro line, or defense vessel, L&T is virtually guaranteed to build it.",
            risk_level="Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="BHARTIARTL.NS",
            name="Bharti Airtel",
            approx_price="₹1,580.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Telecom duopoly in India with premium ARPU growth and expanding enterprise cloud data centers.",
            why_it_matters="Digital utility essential to 350+ million Indians and businesses with strong pricing power.",
            risk_level="Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="HINDUNILVR.NS",
            name="Hindustan Unilever",
            approx_price="₹2,380.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Unrivaled distribution network touching 9 out of 10 Indian households daily across soaps, tea, and detergents.",
            why_it_matters="Ultimate defensive stock. Everyday consumption continues regardless of economic cycles.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="KOTAKBANK.NS",
            name="Kotak Mahindra Bank",
            approx_price="₹1,750.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Conservative risk-adjusted underwriting with one of the lowest non-performing loan ratios in Asia.",
            why_it_matters="Fortress balance sheet built by Uday Kotak to withstand any economic liquidity crunch.",
            risk_level="Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="TATASTEEL.NS",
            name="Tata Steel",
            approx_price="₹145.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Fully captive high-grade iron ore mines making it one of the lowest-cost steelmakers on earth.",
            why_it_matters="Core supplier to automotive and national infrastructure projects with blue-chip Tata lineage.",
            risk_level="Cyclical Blue-Chip",
            risk_badge="🟢 Blue-Chip Value",
        ),
        ThematicStockItem(
            ticker="ASIANPAINT.NS",
            name="Asian Paints",
            approx_price="₹2,250.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Uncontested decorative paints monopoly with over 50 years of uninterrupted market leadership.",
            why_it_matters="Exceptional supply chain logistics and proprietary dealer tinting machines protect its deep moat.",
            risk_level="Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
    ],

    "new": [
        ThematicStockItem(
            ticker="ZOMATO.NS",
            name="Zomato Ltd",
            approx_price="₹245.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Blinkit quick-commerce hypergrowth turning the entire enterprise decisively profitable.",
            why_it_matters="The defining consumer tech platform dominating grocery delivery and dining out across urban India.",
            risk_level="Growth / High Multiple",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="JIOFIN.NS",
            name="Jio Financial Services",
            approx_price="₹315.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Joint venture with BlackRock to disrupt Indian asset management, lending, and digital payments.",
            why_it_matters="Massive capital base with direct distribution access to over 450 million Jio telecom subscribers.",
            risk_level="Emerging Giant",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="SWIGGY.NS",
            name="Swiggy Ltd",
            approx_price="₹410.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Newly listed food delivery and Instamart quick commerce duopoly with expanding dark store margins.",
            why_it_matters="High-frequency urban consumer habit with immense cross-selling power for groceries and dining.",
            risk_level="High Growth",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="TATATECH.NS",
            name="Tata Technologies",
            approx_price="₹880.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Pure-play digital engineering services powering global OEM transitions to EVs and aerospace software.",
            why_it_matters="First Tata Group IPO in almost 20 years, commanding prestigious automotive relationships globally.",
            risk_level="Growth",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="POLICYBZR.NS",
            name="PB Fintech",
            approx_price="₹1,650.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Near-monopoly in online term life and health insurance distribution reaching free cash flow inflection.",
            why_it_matters="Underpenetrated Indian insurance market ensures double-digit structural runway for decades.",
            risk_level="High Growth",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="NYKAA.NS",
            name="FSN E-Commerce (Nykaa)",
            approx_price="₹175.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Dominant beauty and personal care omnichannel retailer expanding owned-brand gross margins.",
            why_it_matters="Pioneered curated luxury cosmetics e-commerce with high brand loyalty among affluent Indian women.",
            risk_level="Growth",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="DELHIVERY.NS",
            name="Delhivery",
            approx_price="₹340.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Fully automated express parcel sortation hubs capturing e-commerce volume inflection.",
            why_it_matters="India's largest independent third-party logistics network with high operating leverage as volumes scale.",
            risk_level="Turnaround Growth",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="MAPMYINDIA.NS",
            name="C.E. Info Systems",
            approx_price="₹1,850.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Monopoly in indigenous digital HD mapping powering automotive ADAS, Apple Maps India, and drone corridors.",
            why_it_matters="Asset-light 40%+ EBITDA margins with unmatched proprietary spatial geospatial intelligence data.",
            risk_level="High Margin Niche",
            risk_badge="🟢 High Moat",
        ),
        ThematicStockItem(
            ticker="PAYTM.NS",
            name="One97 Communications",
            approx_price="₹720.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Post-regulatory pivot toward merchant soundbox subscriptions and third-party bank loan distribution.",
            why_it_matters="Dominant merchant checkout terminal network generating stable recurring software rental fees.",
            risk_level="Speculative Turnaround",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="HONASA.NS",
            name="Honasa Consumer (Mamaearth)",
            approx_price="₹265.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Toxin-free direct-to-consumer brand expanding into offline general trade and pharmacy shelves.",
            why_it_matters="Fast-scaling young personal care portfolio addressing the clean-ingredient consumer shift.",
            risk_level="Growth / Volatile",
            risk_badge="🟡 Moderate",
        ),
    ],

    "trending": [
        ThematicStockItem(
            ticker="TATAMOTORS.NS",
            name="Tata Motors",
            approx_price="₹715.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="70%+ market share in domestic passenger EVs alongside roaring Jaguar Land Rover luxury order book.",
            why_it_matters="Among the most actively traded stocks in India, leading the automotive and clean mobility transformation.",
            risk_level="Moderate",
            risk_badge="🟢 Bullish",
        ),
        ThematicStockItem(
            ticker="BEL.NS",
            name="Bharat Electronics",
            approx_price="₹295.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Record multi-billion rupee defense orders for naval radars, electronic warfare systems, and missile avionics.",
            why_it_matters="The prime hardware beneficiary of the government's mandatory indigenous defense procurement policy.",
            risk_level="Low to Moderate",
            risk_badge="🟢 Bullish",
        ),
        ThematicStockItem(
            ticker="HAL.NS",
            name="Hindustan Aeronautics",
            approx_price="₹4,100.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Sole manufacturer of Tejas fighter aircraft and multi-role combat helicopters with multi-decade order visibility.",
            why_it_matters="Monopolistic sovereign aerospace champion backed by guaranteed Ministry of Defense capital allocations.",
            risk_level="Moderate",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="TRENT.NS",
            name="Trent Ltd",
            approx_price="₹6,400.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Zudio fast-fashion retail phenomenon expanding stores exponentially with industry-leading store-level payback.",
            why_it_matters="Exceptional retail execution by the Tata Group capturing mass discretionary youth fashion spend.",
            risk_level="High Growth / Premium",
            risk_badge="🟡 High Multiple",
        ),
        ThematicStockItem(
            ticker="COCHINSHIP.NS",
            name="Cochin Shipyard",
            approx_price="₹1,450.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Builder of India's indigenous aircraft carrier expanding into green hydrogen commercial vessels and repair docks.",
            why_it_matters="Strategic national defense shipyard with strong export and commercial retrofit order pipeline.",
            risk_level="High Momentum",
            risk_badge="🟢 Bullish",
        ),
        ThematicStockItem(
            ticker="MAZDOCK.NS",
            name="Mazagon Dock Shipbuilders",
            approx_price="₹4,200.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Construction of Scorpene-class submarines and stealth guided-missile destroyers for the Indian Navy.",
            why_it_matters="Premier submarine manufacturing yard with massive order backlogs guaranteeing multi-year revenue growth.",
            risk_level="High Momentum",
            risk_badge="🟢 Bullish",
        ),
        ThematicStockItem(
            ticker="DIXON.NS",
            name="Dixon Technologies",
            approx_price="₹12,800.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Leading electronic manufacturing services (EMS) partner assembling smartphones for Motorola, Xiaomi, and Google.",
            why_it_matters="The primary champion of the government's Production Linked Incentive (PLI) electronics hardware push.",
            risk_level="High Growth",
            risk_badge="🟢 High Growth",
        ),
        ThematicStockItem(
            ticker="BSE.NS",
            name="BSE Ltd",
            approx_price="₹3,900.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Explosive market share gains in weekly index derivatives contracts (Sensex & Bankex).",
            why_it_matters="Pure exchange tollbooth that profits directly from surging retail participation and institutional trading volumes.",
            risk_level="High Momentum",
            risk_badge="🟢 Strong Momentum",
        ),
        ThematicStockItem(
            ticker="RVNL.NS",
            name="Rail Vikas Nigam",
            approx_price="₹390.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Executing dedicated freight corridors, metro rail lines, and overseas railway construction joint ventures.",
            why_it_matters="Primary executing agency for the multi-trillion rupee Indian Railways modernisation capex program.",
            risk_level="High Volatility",
            risk_badge="🟡 High Volatility",
        ),
        ThematicStockItem(
            ticker="ADANIENT.NS",
            name="Adani Enterprises",
            approx_price="₹2,800.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Incubating sovereign mega-projects including airports, green hydrogen, expressways, and data centers.",
            why_it_matters="Flagship incubator driving private infrastructure investment across essential national supply chains.",
            risk_level="High Leverage / Policy",
            risk_badge="🟡 High Volatility",
        ),
    ],

    "future": [
        ThematicStockItem(
            ticker="SUZLON.NS",
            name="Suzlon Energy",
            approx_price="₹58.20",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Prime Minister's sovereign mandate targeting 500 GW of clean non-fossil renewable capacity by 2030.",
            why_it_matters="Essential for meeting India's decarbonization targets with domestic 3 MW wind turbine generators.",
            risk_level="Policy Supercycle",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="IREDA.NS",
            name="IREDA",
            approx_price="₹195.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="State financing backbone underwriting national solar parks, green hydrogen hubs, and EV charging grids.",
            why_it_matters="Nearly every sovereign green infrastructure project in India is financed by IREDA.",
            risk_level="Sovereign Megatrend",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="EXIDEIND.NS",
            name="Exide Industries",
            approx_price="₹420.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Building India's largest lithium-ion battery cell gigafactory with global supply ties to Hyundai and Kia.",
            why_it_matters="Ends India's foreign dependence on imported battery packs for the upcoming EV mass adoption cycle.",
            risk_level="EV Infrastructure",
            risk_badge="🟢 Emerging Leader",
        ),
        ThematicStockItem(
            ticker="TITAGARH.NS",
            name="Titagarh Rail Systems",
            approx_price="₹1,120.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Contractor for Vande Bharat sleeper trainsets and advanced metro train bodies for major Indian smart cities.",
            why_it_matters="Direct beneficiary of government budget allocation toward high-speed modern rail transit.",
            risk_level="Infrastructure Supercycle",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="JSWENERGY.NS",
            name="JSW Energy",
            approx_price="₹640.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Massive pivot toward renewable power with multi-gigawatt battery energy storage systems (BESS).",
            why_it_matters="Solves renewable intermittency by providing round-the-clock baseload green power to commercial grids.",
            risk_level="Energy Transition",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="KPITTECH.NS",
            name="KPIT Technologies",
            approx_price="₹1,350.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Dedicated automotive software partner developing autonomous driving and electric powertrain architectures for global OEMs.",
            why_it_matters="Modern vehicles are computers on wheels. KPIT writes the core operating systems for future cars.",
            risk_level="High Tech Multiple",
            risk_badge="🟢 Secular Growth",
        ),
        ThematicStockItem(
            ticker="TATAELXSI.NS",
            name="Tata Elxsi",
            approx_price="₹6,600.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="High-end industrial design and AI integration across connected autonomous mobility and medical devices.",
            why_it_matters="Premium design arm of Tata Group commanding 25%+ margins and near-zero debt.",
            risk_level="Premium Quality",
            risk_badge="🟢 Safe Compounder",
        ),
        ThematicStockItem(
            ticker="DEEPAKFERT.NS",
            name="Deepak Fertilisers",
            approx_price="₹950.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Commissioning specialized nitric acid and electronic-grade chemicals required for solar and semiconductor fabs.",
            why_it_matters="Critical chemical feedstock supplier powering domestic mining, defense, and high-tech manufacturing.",
            risk_level="Industrial Cyclical",
            risk_badge="🟡 Emerging Value",
        ),
        ThematicStockItem(
            ticker="L&TFH.NS",
            name="L&T Finance Holdings",
            approx_price="₹140.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Lakshya 2026 transformation into a 95%+ retail lender focusing on rural inclusion and farm tractors.",
            why_it_matters="Direct proxy on rural disposable income growth and agricultural mechanization in Bharat.",
            risk_level="Financial Inclusion",
            risk_badge="🟢 High Dividend",
        ),
        ThematicStockItem(
            ticker="PRESTIGE.NS",
            name="Prestige Estates",
            approx_price="₹1,600.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Premium residential and commercial office real estate boom across Bengaluru, Mumbai, and Hyderabad.",
            why_it_matters="Captures the generational urbanization and wealth accumulation of India's technology workforce.",
            risk_level="Real Estate Growth",
            risk_badge="🟢 Strong Momentum",
        ),
    ],
}


# =============================================================================
# US MARKETS (NYSE / NASDAQ) THEMATIC RADAR — EXPANDED INSTITUTIONAL UNIVERSE
# =============================================================================
US_THEMATIC_RADAR: Dict[str, List[ThematicStockItem]] = {
    "penny": [
        ThematicStockItem(
            ticker="BBAI",
            name="BigBear.ai",
            approx_price="$1.95",
            category_id="penny",
            category_title="🪙 Small-Priced (< $10)",
            catalyst_driver="AI decision-support contractor securing US Department of Defense and airport biometrics deals.",
            why_it_matters="Micro-cap price with sovereign government backing, though prone to wide percentage swings.",
            risk_level="Speculative Contractor",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="OPEN",
            name="Opendoor Technologies",
            approx_price="$1.90",
            category_id="penny",
            category_title="🪙 Small-Priced (< $10)",
            catalyst_driver="Algorithmic digital real estate e-commerce platform highly sensitive to Federal Reserve interest rate cuts.",
            why_it_matters="High operating leverage turnaround play as US mortgage rates ease and existing home sales recover.",
            risk_level="Rate Sensitive / Speculative",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="PLUG",
            name="Plug Power",
            approx_price="$2.10",
            category_id="penny",
            category_title="🪙 Small-Priced (< $10)",
            catalyst_driver="Green hydrogen ecosystem and fuel cell infrastructure subsidized by US Department of Energy loans.",
            why_it_matters="Sub-$5 energy transition stock; highly volatile and dependent on clean energy policy support.",
            risk_level="Cash Burn Warning",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="CLOV",
            name="Clover Health",
            approx_price="$3.10",
            category_id="penny",
            category_title="🪙 Small-Priced (< $10)",
            catalyst_driver="AI-driven healthcare SaaS platform (Clover Assistant) reaching positive GAAP operational profitability.",
            why_it_matters="Turnaround in Medicare Advantage insurance using predictive data to cut patient hospitalization costs.",
            risk_level="Healthcare Turnaround",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="ACHR",
            name="Archer Aviation",
            approx_price="$4.10",
            category_id="penny",
            category_title="🪙 Small-Priced (< $10)",
            catalyst_driver="FAA commercial certification of 'Midnight' electric air taxis with strategic backing from United Airlines and Stellantis.",
            why_it_matters="Leading the future of urban air mobility to bypass crowded metropolitan highway traffic.",
            risk_level="Pre-Revenue Frontier",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="SOUN",
            name="SoundHound AI",
            approx_price="$4.85",
            category_id="penny",
            category_title="🪙 Small-Priced (< $10)",
            catalyst_driver="Voice-AI platform partnered with NVIDIA, Stellantis, and major enterprise restaurant chains.",
            why_it_matters="Low dollar entry to the AI wave. High volatility, but rapidly compounding enterprise backlog.",
            risk_level="High Risk / Speculative",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="JOBY",
            name="Joby Aviation",
            approx_price="$5.30",
            category_id="penny",
            category_title="🪙 Small-Priced (< $10)",
            catalyst_driver="Electric vertical takeoff and landing (eVTOL) pioneer with $500M investment from Toyota and Delta Air Lines.",
            why_it_matters="Advanced testing stages with the FAA to operate zero-emission aerial airport shuttles by 2025/2026.",
            risk_level="Frontier Mobility",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="DNA",
            name="Ginkgo Bioworks",
            approx_price="$7.50",
            category_id="penny",
            category_title="🪙 Small-Priced (< $10)",
            catalyst_driver="Cell programming platform providing biological foundry services for pharmaceuticals and agriculture.",
            why_it_matters="Pioneering the biological revolution where cells are programmed like computers, backed by major pharma royalties.",
            risk_level="Biotech Platform",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="ASTS",
            name="AST SpaceMobile",
            approx_price="$8.50",
            category_id="penny",
            category_title="🪙 Small-Priced (< $10)",
            catalyst_driver="Space-based cellular broadband network connecting directly to standard everyday smartphones from low Earth orbit.",
            why_it_matters="Commercial deals with AT&T, Verizon, and Google with the potential to eradicate global cellular dead zones.",
            risk_level="High Growth / Space",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="LUNR",
            name="Intuitive Machines",
            approx_price="$9.20",
            category_id="penny",
            category_title="🪙 Small-Priced (< $10)",
            catalyst_driver="First commercial company to land on the Moon under NASA's multi-billion dollar Artemis program.",
            why_it_matters="Frontier space economy play holding exclusive NASA lunar telemetry and satellite communications contracts.",
            risk_level="Space Economy",
            risk_badge="🟡 Speculative",
        ),
        ThematicStockItem(
            ticker="RKLB",
            name="Rocket Lab USA",
            approx_price="$9.80",
            category_id="penny",
            category_title="🪙 Small-Priced (< $10)",
            catalyst_driver="Proven Electron small-rocket launch cadence and development of the larger reusable Neutron rocket.",
            why_it_matters="The undisputed #2 commercial rocket launcher behind SpaceX with profitable satellite component manufacturing.",
            risk_level="High Growth",
            risk_badge="🟢 High Conviction",
        ),
    ],

    "safe": [
        ThematicStockItem(
            ticker="MSFT",
            name="Microsoft Corporation",
            approx_price="$430.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Monopolies in Windows, Office 365, Azure Cloud, and multi-billion stake in OpenAI.",
            why_it_matters="One of only two companies on Earth with a pristine AAA credit rating (higher than the US Government).",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="AAPL",
            name="Apple Inc.",
            approx_price="$228.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="2.2+ billion active devices worldwide creating an unbeatable high-margin Services software flywheel.",
            why_it_matters="Generates over $100 Billion in annual free cash flow and routinely buys back billions of its own stock.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="BRK-B",
            name="Berkshire Hathaway",
            approx_price="$460.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Warren Buffett's conglomerate holding over $300 Billion in cash reserves and Treasury bills.",
            why_it_matters="The ultimate defensive fortress during market downturns. Compounds steadily with pristine safety.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="GOOGL",
            name="Alphabet Inc.",
            approx_price="$175.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Global monopoly in Search, YouTube ad revenue, Google Cloud profitability, and Waymo autonomous leadership.",
            why_it_matters="Massive cash generator with world-leading deep AI research capabilities through Google DeepMind.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="AMZN",
            name="Amazon.com",
            approx_price="$195.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Dominance in global e-commerce and high-margin AWS cloud infrastructure powering generative AI workloads.",
            why_it_matters="Unmatched logistics and fulfillment network that would cost hundreds of billions of dollars to replicate.",
            risk_level="Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="JNJ",
            name="Johnson & Johnson",
            approx_price="$162.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Pharmaceutical and medical devices giant with 62 consecutive years of increasing its dividend payout.",
            why_it_matters="People need life-saving medicine and surgical equipment regardless of economic recessions.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="JPM",
            name="JPMorgan Chase & Co.",
            approx_price="$225.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="The most profitable tier-1 bank in global history, overseen by Jamie Dimon with fortress tier-1 capital.",
            why_it_matters="During banking stress, deposits flee regional competitors directly into JPMorgan for safety.",
            risk_level="Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="V",
            name="Visa Inc.",
            approx_price="$285.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Global payments network duopoly commanding incredible 50%+ operating margins on every swipe.",
            why_it_matters="Asset-light tollbooth on global consumer spending that acts as a natural hedge against inflation.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="PG",
            name="Procter & Gamble",
            approx_price="$170.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Dominant consumer essentials portfolio (Tide, Pampers, Gillette) with exceptional brand pricing power.",
            why_it_matters="Classic defensive staple that has paid growing dividends for over 67 consecutive years.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="COST",
            name="Costco Wholesale",
            approx_price="$890.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="93%+ annual membership renewal rates and high volume bulk buying power shielding consumers from inflation.",
            why_it_matters="Legendary consumer loyalty and steady compounding with virtually zero inventory obsolescence risk.",
            risk_level="Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="KO",
            name="The Coca-Cola Company",
            approx_price="$68.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Unrivaled global beverage distribution footprint in over 200 nations with 62-year dividend king status.",
            why_it_matters="Warren Buffett's favorite compounder that reliably pays income in all economic weather conditions.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="WMT",
            name="Walmart Inc.",
            approx_price="$88.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="World's largest retailer capturing high-income shoppers and expanding automated retail media advertising.",
            why_it_matters="The bedrock of American retail with an unmatched grocery distribution supply chain.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
    ],

    "new": [
        ThematicStockItem(
            ticker="ARM",
            name="Arm Holdings",
            approx_price="$135.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Power-efficient chip architecture used inside 99% of smartphones and rapidly taking over AI cloud servers.",
            why_it_matters="Recent high-profile IPO that collects a royalty license fee on every advanced computing chip sold.",
            risk_level="Growth / High Multiple",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="RDDT",
            name="Reddit Inc.",
            approx_price="$110.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Newly public platform licensing proprietary human conversational data to Google and OpenAI for model training.",
            why_it_matters="Fastest-growing community discussion platform converting user interaction into pure high-margin AI licensing revenue.",
            risk_level="High Growth",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="ALAB",
            name="Astera Labs",
            approx_price="$72.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Specialized PCIe connectivity chips linking thousands of GPUs together inside AI datacenter clusters.",
            why_it_matters="Critical 'picks-and-shovels' component provider for hyperscale datacenters run by Amazon, Microsoft, and Google.",
            risk_level="Growth / Tech",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="CAVA",
            name="CAVA Group",
            approx_price="$130.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="High-growth Mediterranean fast-casual dining chain achieving industry-leading same-store sales comps.",
            why_it_matters="Widely viewed on Wall Street as the next Chipotle with decades of national store expansion runway.",
            risk_level="High Multiple Growth",
            risk_badge="🟡 High Multiple",
        ),
        ThematicStockItem(
            ticker="KVYO",
            name="Klaviyo",
            approx_price="$35.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Intelligent marketing automation and customer data platform deeply integrated into Shopify storefronts.",
            why_it_matters="Essential software infrastructure for direct-to-consumer digital commerce generating strong cash flows.",
            risk_level="Growth SaaS",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="CART",
            name="Maplebear (Instacart)",
            approx_price="$42.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Dominant North American grocery delivery marketplace expanding into high-margin retail media advertising.",
            why_it_matters="Partnered with over 1,500 grocery banners with strong cash generation and share repurchase programs.",
            risk_level="Moderate",
            risk_badge="🟢 Cash Flow Positive",
        ),
        ThematicStockItem(
            ticker="BIRK",
            name="Birkenstock Holding",
            approx_price="$50.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Centuries-old heritage footwear brand executing successful direct-to-consumer expansion backed by LVMH.",
            why_it_matters="Cult consumer following with strong gross margins and pricing power in premium casual footwear.",
            risk_level="Consumer Luxury",
            risk_badge="🟢 Brand Moat",
        ),
        ThematicStockItem(
            ticker="TOST",
            name="Toast Inc.",
            approx_price="$32.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="All-in-one cloud POS and payment operating system powering over 100,000 independent restaurant locations.",
            why_it_matters="Sticky restaurant operating system benefiting from cashless transactions and recurring software SaaS fees.",
            risk_level="Growth / Fintech",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="RIVN",
            name="Rivian Automotive",
            approx_price="$11.50",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Electric R1T and R2 platform launch backed by a landmark $5 Billion software partnership with Volkswagen.",
            why_it_matters="High engineering capability and Amazon commercial delivery van fleet contract, though capital intensive.",
            risk_level="High Volatility / EV",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="DUOL",
            name="Duolingo",
            approx_price="$280.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors",
            catalyst_driver="Gamified language and education platform achieving viral user growth with generative AI conversation tutors.",
            why_it_matters="Exceptional subscription conversion rate and operating leverage with zero debt on the balance sheet.",
            risk_level="High Growth",
            risk_badge="🟢 High Quality",
        ),
    ],

    "trending": [
        ThematicStockItem(
            ticker="NVDA",
            name="NVIDIA Corporation",
            approx_price="$128.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="The supreme hardware engine of generative AI with insatiable worldwide demand for Blackwell architecture GPUs.",
            why_it_matters="The #1 most watched and traded stock in the world today. Sets the tone for the entire global technology sector.",
            risk_level="High Momentum",
            risk_badge="🟢 Bullish",
        ),
        ThematicStockItem(
            ticker="TSLA",
            name="Tesla Inc.",
            approx_price="$235.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Cybercab autonomous robotaxi unveil, Full Self-Driving v13, and scaling Megapack grid energy storage.",
            why_it_matters="Extreme retail and institutional liquidity with unmatched retail interest in autonomous transport and robotics.",
            risk_level="High Volatility",
            risk_badge="🟡 Caution",
        ),
        ThematicStockItem(
            ticker="PLTR",
            name="Palantir Technologies",
            approx_price="$58.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="S&P 500 inclusion and massive adoption of its Artificial Intelligence Platform (AIP) by defense and commercial firms.",
            why_it_matters="High-conviction institutional and retail compounder expanding operating margins at extraordinary speed.",
            risk_level="High Momentum",
            risk_badge="🟢 Bullish",
        ),
        ThematicStockItem(
            ticker="AMD",
            name="Advanced Micro Devices",
            approx_price="$155.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="MI300X AI GPU accelerators capturing datacenter share alongside dominant EPYC server processor sales.",
            why_it_matters="The prime viable alternative to NVIDIA in hyperscale AI computing under CEO Lisa Su.",
            risk_level="Momentum",
            risk_badge="🟢 Bullish",
        ),
        ThematicStockItem(
            ticker="META",
            name="Meta Platforms",
            approx_price="$585.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Open-source Llama AI models supercharging ad conversions across 3.2 billion daily active users on Instagram and WhatsApp.",
            why_it_matters="Printing massive free cash flow while leading the global open-source artificial intelligence movement.",
            risk_level="Low to Moderate",
            risk_badge="🟢 Safe Compounder",
        ),
        ThematicStockItem(
            ticker="SMCI",
            name="Super Micro Computer",
            approx_price="$45.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Leading designer of custom liquid-cooled server rack solutions for high-density NVIDIA Blackwell clusters.",
            why_it_matters="High beta AI hardware player experiencing elevated volatility amid accounting auditor turnover.",
            risk_level="High Volatility",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="COIN",
            name="Coinbase Global",
            approx_price="$215.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Official custodian for 80%+ of spot Bitcoin and Ethereum ETFs approved by the US SEC.",
            why_it_matters="Primary regulated gateway for Wall Street institutional capital to interact with digital assets and stablecoins.",
            risk_level="Crypto Beta",
            risk_badge="🟡 High Volatility",
        ),
        ThematicStockItem(
            ticker="HOOD",
            name="Robinhood Markets",
            approx_price="$28.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Rapid expansion into desktop trading, Gold subscriptions, credit cards, and international crypto markets.",
            why_it_matters="Benefiting directly from retail trading resurgence and rising interest income on customer cash deposits.",
            risk_level="Fintech Growth",
            risk_badge="🟢 Bullish",
        ),
        ThematicStockItem(
            ticker="U",
            name="Unity Software",
            approx_price="$22.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Restructured management resetting pricing models for mobile game developers and spatial computing simulations.",
            why_it_matters="Powers over 60% of all mobile games globally; turnaround candidate under new operational leadership.",
            risk_level="Turnaround",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="MSTR",
            name="MicroStrategy",
            approx_price="$220.00",
            category_id="trending",
            category_title="🔥 Trending Today",
            catalyst_driver="Pioneered institutional Bitcoin treasury reserve strategy, accumulating over 250,000 BTC.",
            why_it_matters="Extreme volatility proxy for Bitcoin adoption traded heavily by institutional hedge funds.",
            risk_level="High Volatility",
            risk_badge="🔴 Speculative",
        ),
    ],

    "future": [
        ThematicStockItem(
            ticker="VRT",
            name="Vertiv Holdings",
            approx_price="$112.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Liquid immersion cooling systems and critical power architecture required for high-density AI data centers.",
            why_it_matters="Next-gen AI chips generate so much thermal heat that traditional air conditioning is obsolete. Liquid cooling is mandatory.",
            risk_level="Infrastructure Supercycle",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="CEG",
            name="Constellation Energy",
            approx_price="$260.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Landmark 20-year power contract with Microsoft to restart Three Mile Island nuclear unit for clean AI electricity.",
            why_it_matters="World leaders recognize that nuclear baseload is the only zero-carbon source capable of 24/7 AI power.",
            risk_level="Nuclear Renaissance",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="ETN",
            name="Eaton Corporation",
            approx_price="$350.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Multi-trillion dollar modernization of the US electrical grid to handle EVs, clean power, and AI campuses.",
            why_it_matters="Substation transformers and switchgear equipment are sold out years in advance with immense pricing power.",
            risk_level="Grid Modernization",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="CCJ",
            name="Cameco Corporation",
            approx_price="$55.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Largest pure-play uranium miner in Western nations holding ownership in Westinghouse nuclear reactors.",
            why_it_matters="Severe structural deficit in global uranium fuel supply as 60+ new nuclear reactors are constructed worldwide.",
            risk_level="Commodity Supercycle",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="XYL",
            name="Xylem Inc.",
            approx_price="$135.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Global leader in smart water metering, municipal wastewater treatment, and industrial desalination equipment.",
            why_it_matters="Planetary freshwater scarcity and aging water piping networks represent a non-discretionary global capex cycle.",
            risk_level="Resource Scarcity",
            risk_badge="🟢 Safe Compounder",
        ),
        ThematicStockItem(
            ticker="LLY",
            name="Eli Lilly and Company",
            approx_price="$880.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Mounjaro and Zepbound GLP-1 treatments addressing the multi-billion dollar global obesity and diabetes epidemic.",
            why_it_matters="Projected to become the first pharmaceutical company to achieve a $1 Trillion market valuation.",
            risk_level="Healthcare Supercycle",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="NVO",
            name="Novo Nordisk",
            approx_price="$120.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Ozempic and Wegovy pioneer transforming metabolic health, cardiovascular care, and kidney disease prevention.",
            why_it_matters="Deep manufacturing moat and clinical data dominance in preventative metabolic healthcare.",
            risk_level="Healthcare Supercycle",
            risk_badge="🟢 Safe Compounder",
        ),
        ThematicStockItem(
            ticker="GEV",
            name="GE Vernova",
            approx_price="$270.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="Pure-play power generation spinoff supplying high-efficiency gas turbines, wind blades, and grid software.",
            why_it_matters="Utilities worldwide are ordering gas turbines at record rates to bridge the power gap for hyperscale datacenters.",
            risk_level="Power Supercycle",
            risk_badge="🟢 Strong Momentum",
        ),
        ThematicStockItem(
            ticker="CRWD",
            name="CrowdStrike Holdings",
            approx_price="$295.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="AI-native Falcon platform defending cloud endpoints against state-sponsored and autonomous cyber threats.",
            why_it_matters="Cybersecurity is a mandatory sovereign defense expenditure with high customer contract retention.",
            risk_level="High Quality Growth",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="AXON",
            name="Axon Enterprise",
            approx_price="$430.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (Supercycles)",
            catalyst_driver="TASER devices, body cameras, and AI-powered evidence management modernizing global law enforcement.",
            why_it_matters="Dominant public safety monopoly expanding software SaaS subscriptions with virtually zero customer churn.",
            risk_level="Defense & Safety",
            risk_badge="🟢 High Conviction",
        ),
    ],
}


def get_thematic_market_radar(is_indian: bool = False) -> Dict[str, List[ThematicStockItem]]:
    """Returns curated thematic discovery lists synchronized to the selected stock exchange."""
    return INDIAN_THEMATIC_RADAR if is_indian else US_THEMATIC_RADAR
