from dataclasses import dataclass
from typing import Dict, List


@dataclass
class ThematicStockItem:
    """Represents a curated stock discovery item with beginner-friendly context."""
    ticker: str
    name: str
    approx_price: str
    category_id: str  # 'penny', 'safe', 'new', 'trending', 'future'
    category_title: str
    catalyst_driver: str
    why_it_matters: str
    risk_level: str
    risk_badge: str  # '🟢 Safe', '🟡 Moderate', '🔴 High Risk'


# Indian Markets (NSE / BSE) Thematic Radar
INDIAN_THEMATIC_RADAR: Dict[str, List[ThematicStockItem]] = {
    "penny": [
        ThematicStockItem(
            ticker="IDEA.NS",
            name="Vodafone Idea",
            approx_price="₹7.40",
            category_id="penny",
            category_title="🪙 Small-Priced / Penny Stocks (< ₹100)",
            catalyst_driver="Government debt-equity conversion and fundraising for 5G network rollout.",
            why_it_matters="Very cheap per share, but company has massive legacy debt. High reward if turned around, but high risk.",
            risk_level="High Risk / Speculative",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="YESBANK.NS",
            name="Yes Bank",
            approx_price="₹19.80",
            category_id="penny",
            category_title="🪙 Small-Priced / Penny Stocks (< ₹100)",
            catalyst_driver="Post-restructuring turnaround backed by major Indian banks and rising retail deposits.",
            why_it_matters="Affordable entry price for beginners. Recovering from old bad loans, now stabilizing.",
            risk_level="Speculative Recovery",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="NHPC.NS",
            name="NHPC Ltd",
            approx_price="₹88.50",
            category_id="penny",
            category_title="🪙 Small-Priced / Penny Stocks (< ₹100)",
            catalyst_driver="State-run clean hydropower titan benefiting from national green energy mandates.",
            why_it_matters="Under ₹100, backed by the Indian Government, and pays healthy dividends regularly.",
            risk_level="Low to Moderate Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="SUZLON.NS",
            name="Suzlon Energy",
            approx_price="₹58.20",
            category_id="penny",
            category_title="🪙 Small-Priced / Penny Stocks (< ₹100)",
            catalyst_driver="Turned virtually debt-free with a multi-gigawatt record order book for wind energy.",
            why_it_matters="Massive turnaround story in renewable energy, though prone to sharp short-term swings.",
            risk_level="High Growth / Volatile",
            risk_badge="🟡 Moderate",
        ),
    ],
    "safe": [
        ThematicStockItem(
            ticker="RELIANCE.NS",
            name="Reliance Industries",
            approx_price="₹1,230.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="India's largest conglomerate spanning Oil-to-Chemicals, Jio Telecom, and Retail.",
            why_it_matters="Virtually recession-proof. It is the foundational pillar of the Indian stock market index.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="TCS.NS",
            name="Tata Consultancy Services",
            approx_price="₹3,950.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Zero debt, unmatched 35%+ Return on Equity, and consistent high dividend distributions.",
            why_it_matters="When markets crash, TCS protects investor capital thanks to rock-solid global contracts.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="HDFCBANK.NS",
            name="HDFC Bank",
            approx_price="₹1,680.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="India's premier private banking institution with conservative lending and pristine asset quality.",
            why_it_matters="The core anchor for institutional domestic and foreign investment in Indian finance.",
            risk_level="Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="ITC.NS",
            name="ITC Limited",
            approx_price="₹465.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Monopoly cigarette cash cow funding rapid growth in packaged foods, hotels, and paperboards.",
            why_it_matters="Famed for defensive stability during market panics and generous quarterly dividend payouts.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
    ],
    "new": [
        ThematicStockItem(
            ticker="ZOMATO.NS",
            name="Zomato Ltd",
            approx_price="₹245.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors (Recent IPOs)",
            catalyst_driver="Hypergrowth in quick-commerce (Blinkit) turning company solidly profitable.",
            why_it_matters="New generation consumer giant dominating grocery and food delivery across urban India.",
            risk_level="Growth / High Multiple",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="JIOFIN.NS",
            name="Jio Financial Services",
            approx_price="₹315.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors (Recent IPOs)",
            catalyst_driver="Spun off from Reliance, partnering with BlackRock for low-cost Indian wealth management.",
            why_it_matters="Enormous capital reserves and access to 450+ million Jio subscribers for loans and insurance.",
            risk_level="Growth / Long Term",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="TATATECH.NS",
            name="Tata Technologies",
            approx_price="₹880.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors (Recent IPOs)",
            catalyst_driver="Pure-play digital engineering and product development for global electric vehicles and aerospace.",
            why_it_matters="First Tata Group IPO in nearly two decades, with world-class engineering talent.",
            risk_level="Growth / Moderate",
            risk_badge="🟡 Moderate",
        ),
    ],
    "trending": [
        ThematicStockItem(
            ticker="TATAMOTORS.NS",
            name="Tata Motors",
            approx_price="₹715.00",
            category_id="trending",
            category_title="🔥 Trending Today (Viral News & High Volume)",
            catalyst_driver="Dominant #1 market share in Indian passenger EVs and roaring global Jaguar Land Rover demand.",
            why_it_matters="Among the most actively traded stocks in India, leading the automotive revival.",
            risk_level="Moderate Risk",
            risk_badge="🟢 Bullish",
        ),
        ThematicStockItem(
            ticker="BEL.NS",
            name="Bharat Electronics",
            approx_price="₹295.00",
            category_id="trending",
            category_title="🔥 Trending Today (Viral News & High Volume)",
            catalyst_driver="Record multi-billion rupee defense orders from the Ministry of Defense for radar and electronic warfare.",
            why_it_matters="Primary hardware supplier for the Indian Armed Forces under the 'Make in India' defense mandate.",
            risk_level="Low to Moderate",
            risk_badge="🟢 Bullish",
        ),
        ThematicStockItem(
            ticker="TRENT.NS",
            name="Trent Ltd",
            approx_price="₹6,400.00",
            category_id="trending",
            category_title="🔥 Trending Today (Viral News & High Volume)",
            catalyst_driver="Fast-fashion juggernaut (Zudio) achieving record store openings and industry-beating sales.",
            why_it_matters="Massive multi-bagger stock capturing the rising discretionary spending of youth across India.",
            risk_level="High Growth / Premium",
            risk_badge="🟡 Caution",
        ),
    ],
    "future": [
        ThematicStockItem(
            ticker="SUZLON.NS",
            name="Suzlon Energy",
            approx_price="₹58.20",
            category_id="future",
            category_title="🚀 Future Mega-Trends (World Leaders & Next-Decade Supercycles)",
            catalyst_driver="Prime Minister's national target of 500 GW non-fossil renewable capacity by 2030.",
            why_it_matters="Essential for meeting India's sovereign clean energy commitments over the next 10 years.",
            risk_level="Policy Supercycle",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="IREDA.NS",
            name="IREDA",
            approx_price="₹195.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (World Leaders & Next-Decade Supercycles)",
            catalyst_driver="Government financing backbone funding solar parks, green hydrogen, and EV infrastructure.",
            why_it_matters="Every green project sanctioned by the Indian government relies on IREDA financing.",
            risk_level="Sovereign Megatrend",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="EXIDEIND.NS",
            name="Exide Industries",
            approx_price="₹420.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (World Leaders & Next-Decade Supercycles)",
            catalyst_driver="Building India's largest lithium-ion battery gigafactory with Hyundai & Kia supply agreements.",
            why_it_matters="Direct play on domestic battery cell manufacturing to end reliance on foreign battery imports.",
            risk_level="EV Infrastructure",
            risk_badge="🟡 Emerging Leader",
        ),
        ThematicStockItem(
            ticker="TITAGARH.NS",
            name="Titagarh Rail Systems",
            approx_price="₹1,120.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (World Leaders & Next-Decade Supercycles)",
            catalyst_driver="Indian Railways multi-trillion rupee modernization, Vande Bharat trainsets, and metro coaches.",
            why_it_matters="Direct beneficiary of government budget allocations toward high-speed modern rail transport.",
            risk_level="Infrastructure Supercycle",
            risk_badge="🟢 High Conviction",
        ),
    ],
}


# US Markets (NYSE / NASDAQ) Thematic Radar
US_THEMATIC_RADAR: Dict[str, List[ThematicStockItem]] = {
    "penny": [
        ThematicStockItem(
            ticker="SOUN",
            name="SoundHound AI",
            approx_price="$4.85",
            category_id="penny",
            category_title="🪙 Small-Priced / Sub-$10 Stocks",
            catalyst_driver="Voice-AI platform partnered with NVIDIA, Stellantis, and major enterprise restaurant chains.",
            why_it_matters="Very cheap per-share entry to the AI wave. High volatility, but rapidly expanding customer base.",
            risk_level="High Risk / Speculative",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="BBAI",
            name="BigBear.ai",
            approx_price="$1.95",
            category_id="penny",
            category_title="🪙 Small-Priced / Sub-$10 Stocks",
            catalyst_driver="AI decision-support contractor securing US Department of Defense and airport security deals.",
            why_it_matters="Micro-cap price with sovereign government backing, though prone to wide percentage swings.",
            risk_level="Speculative Contractor",
            risk_badge="🔴 High Risk",
        ),
        ThematicStockItem(
            ticker="ASTS",
            name="AST SpaceMobile",
            approx_price="$8.50",
            category_id="penny",
            category_title="🪙 Small-Priced / Sub-$10 Stocks",
            catalyst_driver="Space-based cellular broadband network connecting directly to standard everyday smartphones.",
            why_it_matters="Backed by AT&T, Verizon, and Google. High potential to eliminate global cellular dead zones.",
            risk_level="High Growth / Frontier",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="PLUG",
            name="Plug Power",
            approx_price="$2.10",
            category_id="penny",
            category_title="🪙 Small-Priced / Sub-$10 Stocks",
            catalyst_driver="Green hydrogen ecosystem subsidized by US Department of Energy loan guarantees.",
            why_it_matters="Sub-$5 energy transition stock; highly sensitive to interest rates and federal policy support.",
            risk_level="High Cash Burn Risk",
            risk_badge="🔴 High Risk",
        ),
    ],
    "safe": [
        ThematicStockItem(
            ticker="MSFT",
            name="Microsoft Corporation",
            approx_price="$430.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Monopolies in Windows, Office 365, Azure Cloud, and multi-billion stake in OpenAI.",
            why_it_matters="One of only two companies on Earth with a pristine AAA credit rating (higher than the US Government).",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="AAPL",
            name="Apple Inc.",
            approx_price="$228.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Unmatched customer loyalty with over 2.2 billion active devices worldwide and Apple Intelligence.",
            why_it_matters="Generates over $100 Billion in annual free cash flow and routinely buys back its own stock.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="BRK-B",
            name="Berkshire Hathaway",
            approx_price="$460.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Warren Buffett's conglomerate holding over $300 Billion in pure cash reserves and short-term Treasuries.",
            why_it_matters="The ultimate defensive fortress during market downturns. Never pays a dividend but compounds steadily.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
        ThematicStockItem(
            ticker="JNJ",
            name="Johnson & Johnson",
            approx_price="$162.00",
            category_id="safe",
            category_title="🏰 Safe Havens (Fortress Blue-Chips)",
            catalyst_driver="Pharma and medical devices giant with 62 consecutive years of increasing its dividend payout.",
            why_it_matters="People need life-saving medicine regardless of whether the economy is booming or in a recession.",
            risk_level="Very Low Risk",
            risk_badge="🟢 Safe Haven",
        ),
    ],
    "new": [
        ThematicStockItem(
            ticker="ARM",
            name="Arm Holdings",
            approx_price="$135.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors (Recent IPOs)",
            catalyst_driver="Chip architecture used inside 99% of all smartphones and now rapidly conquering AI cloud servers.",
            why_it_matters="Recent high-profile IPO that earns a royalty check every single time an advanced processor is sold.",
            risk_level="Growth / High Multiple",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="RDDT",
            name="Reddit Inc.",
            approx_price="$110.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors (Recent IPOs)",
            catalyst_driver="Newly public social platform licensing authentic human discussion data to Google and OpenAI.",
            why_it_matters="Fastest-growing community content platform turning into a high-margin AI training data provider.",
            risk_level="High Growth",
            risk_badge="🟡 Moderate",
        ),
        ThematicStockItem(
            ticker="ALAB",
            name="Astera Labs",
            approx_price="$72.00",
            category_id="new",
            category_title="🌱 New & Emerging Disruptors (Recent IPOs)",
            catalyst_driver="Specialized PCIe semiconductor connectivity chips linking GPUs together in AI clusters.",
            why_it_matters="A critical 'picks-and-shovels' player for hyperscale AI datacenters run by Amazon and Microsoft.",
            risk_level="Growth / Tech",
            risk_badge="🟡 Moderate",
        ),
    ],
    "trending": [
        ThematicStockItem(
            ticker="NVDA",
            name="NVIDIA Corporation",
            approx_price="$128.00",
            category_id="trending",
            category_title="🔥 Trending Today (Viral News & High Volume)",
            catalyst_driver="The supreme engine of generative AI with insatiable worldwide demand for Blackwell GPUs.",
            why_it_matters="The #1 most watched and traded stock in the world today. Sets the tone for the entire global tech market.",
            risk_level="High Momentum",
            risk_badge="🟢 Bullish",
        ),
        ThematicStockItem(
            ticker="TSLA",
            name="Tesla Inc.",
            approx_price="$235.00",
            category_id="trending",
            category_title="🔥 Trending Today (Viral News & High Volume)",
            catalyst_driver="Unveiling Cybercab autonomous robotaxis, Full Self-Driving v13, and Optimus humanoid robot factories.",
            why_it_matters="Extreme retail and institutional interest with immense daily trading liquidity.",
            risk_level="High Volatility",
            risk_badge="🟡 Caution",
        ),
        ThematicStockItem(
            ticker="PLTR",
            name="Palantir Technologies",
            approx_price="$58.00",
            category_id="trending",
            category_title="🔥 Trending Today (Viral News & High Volume)",
            catalyst_driver="S&P 500 inclusion and massive adoption of its Artificial Intelligence Platform (AIP) by defense agencies.",
            why_it_matters="Viral popularity among young investors; rapidly expanding from US military to commercial industry.",
            risk_level="High Momentum",
            risk_badge="🟢 Bullish",
        ),
    ],
    "future": [
        ThematicStockItem(
            ticker="VRT",
            name="Vertiv Holdings",
            approx_price="$112.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (World Leaders & Next-Decade Supercycles)",
            catalyst_driver="Liquid immersion cooling and critical power architecture required for massive AI data centers.",
            why_it_matters="NVIDIA chips produce so much heat they can no longer be cooled by air alone. Liquid cooling is mandatory.",
            risk_level="Infrastructure Supercycle",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="CEG",
            name="Constellation Energy",
            approx_price="$260.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (World Leaders & Next-Decade Supercycles)",
            catalyst_driver="Historic deal with Microsoft to restart Three Mile Island nuclear unit to supply 100% clean power.",
            why_it_matters="World leaders are embracing nuclear energy as the only zero-carbon source capable of 24/7 AI power.",
            risk_level="Nuclear Renaissance",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="ETN",
            name="Eaton Corporation",
            approx_price="$350.00",
            category_id="future",
            category_title="🚀 Future Mega-Trends (World Leaders & Next-Decade Supercycles)",
            catalyst_driver="Multi-trillion dollar modernization of the US electrical grid to handle EVs, heat pumps, and data centers.",
            why_it_matters="Transformers and high-voltage grid equipment are sold out years in advance. A massive secular tailwind.",
            risk_level="Grid Electrification",
            risk_badge="🟢 High Conviction",
        ),
        ThematicStockItem(
            ticker="LUNR",
            name="Intuitive Machines",
            approx_price="$9.20",
            category_id="future",
            category_title="🚀 Future Mega-Trends (World Leaders & Next-Decade Supercycles)",
            catalyst_driver="NASA Artemis commercial lunar payload contractor building moon communications and rover rovers.",
            why_it_matters="Frontier space economy play backed by bipartisan congressional NASA budgets for lunar exploration.",
            risk_level="Space Economy",
            risk_badge="🟡 Speculative",
        ),
    ],
}


def get_thematic_market_radar(is_indian: bool = False) -> Dict[str, List[ThematicStockItem]]:
    """Returns curated thematic discovery lists synchronized to the selected stock exchange."""
    return INDIAN_THEMATIC_RADAR if is_indian else US_THEMATIC_RADAR

